-- 김가네 25개 매장 리스크 평가 시드 데이터 (2026-08-10, 216개 백필분 중 25개만
-- 발췌 — 전체는 kimgane_216_risk_assessments_full216_backup.sql 참고)
--
-- 적용 전 확인: SELECT COUNT(*) FROM risk_assessments WHERE store_id IN (1004,1083,1091,1097,1100,1101,1105,1106,1107,1116,1119,1120,1121,1127,1131,1133,1137,1138,1144,1145,1164,1175,1177,1185,1199);

START TRANSACTION;

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1004, 'closure-risk-v1-v2-2026-08', 11.81, 1, NULL, '업종 기준만 판단 — 입지 정보 없음(서울 외 지역 매장)', '같은 업종의 다른 브랜드들도 최근 해지가 잦음(업종 평균 해지율 15.8%) 방향 확인 필요: 배경표본 대비 43백분위로 \'낮음\' 쪽인데, 이 카테고리는 통상 \'높을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '모델 비교군 기준 위험 백분위 11.8%로 분류되었습니다.', '업종 트렌드 정기 모니터링, 업종 내 수요변화 조기경보, 업종 전환 상담 제공', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'induty_peer_avg_discontinuation_rate', '업종 구조적 위험', 0.0017253806831885857, '같은 업종의 다른 브랜드들도 최근 해지가 잦음(업종 평균 해지율 15.8%) 방향 확인 필요: 배경표본 대비 43백분위로 \'낮음\' 쪽인데, 이 카테고리는 통상 \'높을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '업종 트렌드 정기 모니터링, 업종 내 수요변화 조기경보, 업종 전환 상담 제공', '업종 변경 시 계약 승계·조건 조정 조항을 명확히 하고, 최소 매출 기준 재검토 주기를 단축한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'education_fee', '초기 투자비용 부담', 0.0010490494187410698, '초기 투자비용 부담 관련 값이 이 브랜드/매장에 결측 — 모델은 결측을 반영해 판단했으나 구체적 수치는 근거로 제시할 수 없음', '초기비용 부담이 큰 가맹점 대상 재협상 지원', '회수 미달 시 유예/분할 조항을 마련한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'biz_assurance_amt', '초기 투자비용 부담', 0.0005232575104579311, '초기 투자비용 부담 관련 값이 이 브랜드/매장에 결측 — 모델은 결측을 반영해 판단했으나 구체적 수치는 근거로 제시할 수 없음', '초기비용 회수 기간 시뮬레이션 제공', '회수 미달 시 유예/분할 조항을 마련한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1083, 'closure-risk-v1-v2-2026-08', 11.81, 1, NULL, '업종 기준만 판단 — 입지 정보 없음(서울 외 지역 매장)', '같은 업종의 다른 브랜드들도 최근 해지가 잦음(업종 평균 해지율 15.8%) 방향 확인 필요: 배경표본 대비 43백분위로 \'낮음\' 쪽인데, 이 카테고리는 통상 \'높을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '모델 비교군 기준 위험 백분위 11.8%로 분류되었습니다.', '업종 트렌드 정기 모니터링, 업종 내 수요변화 조기경보, 업종 전환 상담 제공', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'induty_peer_avg_discontinuation_rate', '업종 구조적 위험', 0.0016485294694546793, '같은 업종의 다른 브랜드들도 최근 해지가 잦음(업종 평균 해지율 15.8%) 방향 확인 필요: 배경표본 대비 43백분위로 \'낮음\' 쪽인데, 이 카테고리는 통상 \'높을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '업종 트렌드 정기 모니터링, 업종 내 수요변화 조기경보, 업종 전환 상담 제공', '업종 변경 시 계약 승계·조건 조정 조항을 명확히 하고, 최소 매출 기준 재검토 주기를 단축한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'education_fee', '초기 투자비용 부담', 0.0010227305954937272, '초기 투자비용 부담 관련 값이 이 브랜드/매장에 결측 — 모델은 결측을 반영해 판단했으나 구체적 수치는 근거로 제시할 수 없음', '초기비용 부담이 큰 가맹점 대상 재협상 지원', '회수 미달 시 유예/분할 조항을 마련한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'biz_assurance_amt', '초기 투자비용 부담', 0.000554364503186742, '초기 투자비용 부담 관련 값이 이 브랜드/매장에 결측 — 모델은 결측을 반영해 판단했으나 구체적 수치는 근거로 제시할 수 없음', '초기비용 회수 기간 시뮬레이션 제공', '회수 미달 시 유예/분할 조항을 마련한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1091, 'closure-risk-v1-v2-2026-08', 31.03, 2, 31.03, '안전 — 업종·입지 둘 다 양호', '업종(분식) 자체의 기본 위험 수준이 반영됨', '모델 비교군 기준 위험 백분위 31.0%로 분류되었습니다.', '업종별 표준 리스크 관리 템플릿 차등 적용', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'induty_mclas_nm', '업종 분류', 0.04998736569382559, '업종(분식) 자체의 기본 위험 수준이 반영됨', '업종별 표준 리스크 관리 템플릿 차등 적용', '업종 특성을 반영한 표준 재계약 조항 템플릿을 적용한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'franchise_fee_total', '초기 투자비용 부담', 0.048815274228336286, '초기 투자비용 부담 관련 값이 이 브랜드/매장에 결측 — 모델은 결측을 반영해 판단했으나 구체적 수치는 근거로 제시할 수 없음', '초기비용 회수 기간 시뮬레이션 제공', '회수 미달 시 유예/분할 조항을 마련한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'total_initial_cost', '초기 투자비용 부담', 0.029262604919906978, '초기 투자비용 부담 관련 값이 이 브랜드/매장에 결측 — 모델은 결측을 반영해 판단했으나 구체적 수치는 근거로 제시할 수 없음', '초기비용 회수 기간 시뮬레이션 제공, 비용 부담이 큰 가맹점 대상 재협상 지원', '회수 미달 시 유예/분할 조항을 마련한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1097, 'closure-risk-v1-v2-2026-08', 93.06, 5, 93.06, '입지 위험 — 업종은 괜찮으나 이 매장 입지가 나쁨 (상권/접근성 개선 조치)', '행정동 음식 소비지출 798,823,000원 (배경표본 대비 7백분위 — 예상된 방향과 일치)', '모델 비교군 기준 위험 백분위 93.1%로 분류되었습니다.', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'adstrd_fd_expndtr', '행정동 소비지출 저조', 1.1627884956026928, '행정동 음식 소비지출 798,823,000원 (배경표본 대비 7백분위 — 예상된 방향과 일치)', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', '지역 구매력에 연동한 로열티·최소 매출 기준 조정을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'avg_selng_amt_per_store', '상권 매출 침체', 0.9776534182913319, '상권×업종 매장당 추정매출 55,196,571원/월 (배경표본 대비 42백분위 — 예상된 방향과 일치)', '매출 모니터링 주기 단축, 조기 개입', '성과 기반 갱신조건(최소 매출 기준)을 명시한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'sgis_grid_population', '배후인구', 0.6631170504046823, '매장 반경 1km 격자 거주인구 13,468명 (배경표본 대비 20백분위 — 예상된 방향과 일치)', '배후인구가 적은 입지는 배달·픽업 채널 강화 지원', '배후인구 희박 지역은 매출 최소 기준을 배달 매출 포함 기준으로 완화하는 조항을 검토한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1100, 'closure-risk-v1-v2-2026-08', 50.51, 3, 50.51, '안전 — 업종·입지 둘 다 양호', '매장 반경 1km 격자 거주인구 13,108명 (배경표본 대비 20백분위 — 예상된 방향과 일치)', '모델 비교군 기준 위험 백분위 50.5%로 분류되었습니다.', '배후인구가 적은 입지는 배달·픽업 채널 강화 지원', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'sgis_grid_population', '배후인구', 0.8340386698527754, '매장 반경 1km 격자 거주인구 13,108명 (배경표본 대비 20백분위 — 예상된 방향과 일치)', '배후인구가 적은 입지는 배달·픽업 채널 강화 지원', '배후인구 희박 지역은 매출 최소 기준을 배달 매출 포함 기준으로 완화하는 조항을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'adstrd_fd_expndtr', '행정동 소비지출 저조', 0.5622915405108508, '행정동 음식 소비지출 302,417,000원 (배경표본 대비 1백분위 — 예상된 방향과 일치)', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', '지역 구매력에 연동한 로열티·최소 매출 기준 조정을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'trdar_flpop_dinner', '유동인구 저조', 0.2307547250082877, '저녁시간대(17-21시) 유동인구 141,002명 방향 확인 필요: 배경표본 대비 57백분위로 \'높음\' 쪽인데, 이 카테고리는 통상 \'낮을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '저녁 특화 메뉴/프로모션 지원 검토', '유동인구 저조 지역은 매출 최소 기준을 완화하는 조항을 검토한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1101, 'closure-risk-v1-v2-2026-08', 95.78, 5, 95.78, '입지 위험 — 업종은 괜찮으나 이 매장 입지가 나쁨 (상권/접근성 개선 조치)', '행정동 음식 소비지출 890,006,000원 (배경표본 대비 9백분위 — 예상된 방향과 일치)', '모델 비교군 기준 위험 백분위 95.8%로 분류되었습니다.', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'adstrd_fd_expndtr', '행정동 소비지출 저조', 6.3694959295086075, '행정동 음식 소비지출 890,006,000원 (배경표본 대비 9백분위 — 예상된 방향과 일치)', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', '지역 구매력에 연동한 로열티·최소 매출 기준 조정을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'avg_selng_amt_per_store', '상권 매출 침체', 1.5232721389138613, '상권×업종 매장당 추정매출 205,338원/월 (배경표본 대비 0백분위 — 예상된 방향과 일치)', '매출 모니터링 주기 단축, 조기 개입', '성과 기반 갱신조건(최소 매출 기준)을 명시한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'sgis_grid_population', '배후인구', 1.1726627773593283, '매장 반경 1km 격자 거주인구 31,750명 방향 확인 필요: 배경표본 대비 83백분위로 \'높음\' 쪽인데, 이 카테고리는 통상 \'낮을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '배후인구가 적은 입지는 배달·픽업 채널 강화 지원', '배후인구 희박 지역은 매출 최소 기준을 배달 매출 포함 기준으로 완화하는 조항을 검토한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1105, 'closure-risk-v1-v2-2026-08', 15.59, 1, 15.59, '안전 — 업종·입지 둘 다 양호', '매장 반경 1km 격자 거주인구 33,051명 방향 확인 필요: 배경표본 대비 85백분위로 \'높음\' 쪽인데, 이 카테고리는 통상 \'낮을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '모델 비교군 기준 위험 백분위 15.6%로 분류되었습니다.', '배후인구가 적은 입지는 배달·픽업 채널 강화 지원', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'sgis_grid_population', '배후인구', 0.17845049919182865, '매장 반경 1km 격자 거주인구 33,051명 방향 확인 필요: 배경표본 대비 85백분위로 \'높음\' 쪽인데, 이 카테고리는 통상 \'낮을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '배후인구가 적은 입지는 배달·픽업 채널 강화 지원', '배후인구 희박 지역은 매출 최소 기준을 배달 매출 포함 기준으로 완화하는 조항을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'induty_mclas_nm', '업종 분류', 0.1624274272406717, '업종(분식) 자체의 기본 위험 수준이 반영됨', '업종별 표준 리스크 관리 템플릿 차등 적용', '업종 특성을 반영한 표준 재계약 조항 템플릿을 적용한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'franchise_fee_total', '초기 투자비용 부담', 0.04713806667706703, '초기 투자비용 부담 관련 값이 이 브랜드/매장에 결측 — 모델은 결측을 반영해 판단했으나 구체적 수치는 근거로 제시할 수 없음', '초기비용 회수 기간 시뮬레이션 제공', '회수 미달 시 유예/분할 조항을 마련한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1106, 'closure-risk-v1-v2-2026-08', 94.86, 5, 94.86, '입지 위험 — 업종은 괜찮으나 이 매장 입지가 나쁨 (상권/접근성 개선 조치)', '행정동 총 소비지출 2,951,693,000원 (배경표본 대비 6백분위 — 예상된 방향과 일치)', '모델 비교군 기준 위험 백분위 94.9%로 분류되었습니다.', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'adstrd_expndtr_total', '행정동 소비지출 저조', 2.117725749982139, '행정동 총 소비지출 2,951,693,000원 (배경표본 대비 6백분위 — 예상된 방향과 일치)', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', '지역 구매력에 연동한 로열티·최소 매출 기준 조정을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'adstrd_fd_expndtr', '행정동 소비지출 저조', 1.8760316626243467, '행정동 음식 소비지출 156,043,000원 (배경표본 대비 0백분위 — 예상된 방향과 일치)', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', '지역 구매력에 연동한 로열티·최소 매출 기준 조정을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'trdar_flpop', '유동인구 저조', 0.47608567127356455, '상권 총 유동인구 4,114,192명 방향 확인 필요: 배경표본 대비 96백분위로 \'높음\' 쪽인데, 이 카테고리는 통상 \'낮을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '배달·픽업 등 대안 접근성 강화 지원', '유동인구 저조 지역은 매출 최소 기준을 완화하는 조항을 검토한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1107, 'closure-risk-v1-v2-2026-08', 81.59, 5, 81.59, '입지 위험 — 업종은 괜찮으나 이 매장 입지가 나쁨 (상권/접근성 개선 조치)', '최인접 지하철역까지 1,442m (배경표본 대비 96백분위 — 예상된 방향과 일치)', '모델 비교군 기준 위험 백분위 81.6%로 분류되었습니다.', '배달 인프라 투자 우선순위 상향, 접근성 낮은 입지는 간판·동선 개선 검토', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'dist_subway_m', '접근성', 1.3892186580921506, '최인접 지하철역까지 1,442m (배경표본 대비 96백분위 — 예상된 방향과 일치)', '배달 인프라 투자 우선순위 상향, 접근성 낮은 입지는 간판·동선 개선 검토', '접근성이 낮은 입지는 임대료 조건을 재검토하는 조항을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'adstrd_expndtr_total', '행정동 소비지출 저조', 0.7976667013336196, '행정동 총 소비지출 2,714,529,000원 (배경표본 대비 5백분위 — 예상된 방향과 일치)', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', '지역 구매력에 연동한 로열티·최소 매출 기준 조정을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'adstrd_fd_expndtr', '행정동 소비지출 저조', 0.3076077299447097, '행정동 음식 소비지출 414,538,000원 (배경표본 대비 2백분위 — 예상된 방향과 일치)', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', '지역 구매력에 연동한 로열티·최소 매출 기준 조정을 검토한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1116, 'closure-risk-v1-v2-2026-08', 25.18, 2, 25.18, '안전 — 업종·입지 둘 다 양호', '상권 매출 침체 관련 값이 이 브랜드/매장에 결측 — 모델은 결측을 반영해 판단했으나 구체적 수치는 근거로 제시할 수 없음', '모델 비교군 기준 위험 백분위 25.2%로 분류되었습니다.', '매출 모니터링 주기 단축, 조기 개입', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'avg_selng_amt_per_store', '상권 매출 침체', 1.1642837651821805, '상권 매출 침체 관련 값이 이 브랜드/매장에 결측 — 모델은 결측을 반영해 판단했으나 구체적 수치는 근거로 제시할 수 없음', '매출 모니터링 주기 단축, 조기 개입', '성과 기반 갱신조건(최소 매출 기준)을 명시한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'dist_subway_m', '접근성', 0.5197942938200099, '최인접 지하철역까지 1,577m (배경표본 대비 97백분위 — 예상된 방향과 일치)', '배달 인프라 투자 우선순위 상향, 접근성 낮은 입지는 간판·동선 개선 검토', '접근성이 낮은 입지는 임대료 조건을 재검토하는 조항을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'trdar_flpop', '유동인구 저조', 0.5150534405583697, '상권 총 유동인구 225,300명 (배경표본 대비 12백분위 — 예상된 방향과 일치)', '배달·픽업 등 대안 접근성 강화 지원', '유동인구 저조 지역은 매출 최소 기준을 완화하는 조항을 검토한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1119, 'closure-risk-v1-v2-2026-08', 20.03, 2, 20.03, '안전 — 업종·입지 둘 다 양호', '상권 총 유동인구 263,589명 (배경표본 대비 17백분위 — 예상된 방향과 일치)', '모델 비교군 기준 위험 백분위 20.0%로 분류되었습니다.', '배달·픽업 등 대안 접근성 강화 지원', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'trdar_flpop', '유동인구 저조', 0.5945003504896121, '상권 총 유동인구 263,589명 (배경표본 대비 17백분위 — 예상된 방향과 일치)', '배달·픽업 등 대안 접근성 강화 지원', '유동인구 저조 지역은 매출 최소 기준을 완화하는 조항을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'induty_mclas_nm', '업종 분류', 0.247962917469644, '업종(분식) 자체의 기본 위험 수준이 반영됨', '업종별 표준 리스크 관리 템플릿 차등 적용', '업종 특성을 반영한 표준 재계약 조항 템플릿을 적용한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'trdar_flpop_dinner', '유동인구 저조', 0.23834062640277617, '저녁시간대(17-21시) 유동인구 44,815명 (배경표본 대비 13백분위 — 예상된 방향과 일치)', '저녁 특화 메뉴/프로모션 지원 검토', '유동인구 저조 지역은 매출 최소 기준을 완화하는 조항을 검토한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1120, 'closure-risk-v1-v2-2026-08', 96.22, 5, 96.22, '입지 위험 — 업종은 괜찮으나 이 매장 입지가 나쁨 (상권/접근성 개선 조치)', '상권×업종 매장당 추정매출 3,922,507원/월 (배경표본 대비 1백분위 — 예상된 방향과 일치)', '모델 비교군 기준 위험 백분위 96.2%로 분류되었습니다.', '매출 모니터링 주기 단축, 조기 개입', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'avg_selng_amt_per_store', '상권 매출 침체', 3.252152889046376, '상권×업종 매장당 추정매출 3,922,507원/월 (배경표본 대비 1백분위 — 예상된 방향과 일치)', '매출 모니터링 주기 단축, 조기 개입', '성과 기반 갱신조건(최소 매출 기준)을 명시한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'adstrd_fd_expndtr', '행정동 소비지출 저조', 1.5986871741567625, '행정동 음식 소비지출 690,918,000원 (배경표본 대비 3백분위 — 예상된 방향과 일치)', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', '지역 구매력에 연동한 로열티·최소 매출 기준 조정을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'sgis_grid_population', '배후인구', 1.1118651935154757, '매장 반경 1km 격자 거주인구 34,341명 방향 확인 필요: 배경표본 대비 87백분위로 \'높음\' 쪽인데, 이 카테고리는 통상 \'낮을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '배후인구가 적은 입지는 배달·픽업 채널 강화 지원', '배후인구 희박 지역은 매출 최소 기준을 배달 매출 포함 기준으로 완화하는 조항을 검토한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1121, 'closure-risk-v1-v2-2026-08', 97.18, 5, 97.18, '입지 위험 — 업종은 괜찮으나 이 매장 입지가 나쁨 (상권/접근성 개선 조치)', '상권×업종 매장당 추정매출 3,316,874원/월 (배경표본 대비 1백분위 — 예상된 방향과 일치)', '모델 비교군 기준 위험 백분위 97.2%로 분류되었습니다.', '매출 모니터링 주기 단축, 조기 개입', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'avg_selng_amt_per_store', '상권 매출 침체', 4.970023184572988, '상권×업종 매장당 추정매출 3,316,874원/월 (배경표본 대비 1백분위 — 예상된 방향과 일치)', '매출 모니터링 주기 단축, 조기 개입', '성과 기반 갱신조건(최소 매출 기준)을 명시한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'adstrd_expndtr_total', '행정동 소비지출 저조', 1.7982810063784969, '행정동 총 소비지출 4,876,907,000원 (배경표본 대비 17백분위 — 예상된 방향과 일치)', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', '지역 구매력에 연동한 로열티·최소 매출 기준 조정을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'trdar_cls_sale_mt_gap', '상권 쇠퇴 추세', 1.1404116364461716, '그 상권의 폐업 평균 영업개월이 서울 평균 대비 +1.0개월 차이 방향 확인 필요: 배경표본 대비 68백분위로 \'높음\' 쪽인데, 이 카테고리는 통상 \'낮을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '침체 지역 매장 우선 지원(마케팅/리뉴얼), 상권 등급 재평가', '상권 등급 재평가 결과를 갱신조건에 연동하는 조항을 검토한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1127, 'closure-risk-v1-v2-2026-08', 97.84, 5, 97.84, '입지 위험 — 업종은 괜찮으나 이 매장 입지가 나쁨 (상권/접근성 개선 조치)', '행정동 음식 소비지출 999,170,000원 (배경표본 대비 11백분위 — 예상된 방향과 일치)', '모델 비교군 기준 위험 백분위 97.8%로 분류되었습니다.', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'adstrd_fd_expndtr', '행정동 소비지출 저조', 3.8989413648943705, '행정동 음식 소비지출 999,170,000원 (배경표본 대비 11백분위 — 예상된 방향과 일치)', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', '지역 구매력에 연동한 로열티·최소 매출 기준 조정을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'adstrd_expndtr_total', '행정동 소비지출 저조', 1.7130525834511265, '행정동 총 소비지출 4,574,342,000원 (배경표본 대비 17백분위 — 예상된 방향과 일치)', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', '지역 구매력에 연동한 로열티·최소 매출 기준 조정을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'avg_selng_amt_per_store', '상권 매출 침체', 1.5971453604243082, '상권 매출 침체 관련 값이 이 브랜드/매장에 결측 — 모델은 결측을 반영해 판단했으나 구체적 수치는 근거로 제시할 수 없음', '매출 모니터링 주기 단축, 조기 개입', '성과 기반 갱신조건(최소 매출 기준)을 명시한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1131, 'closure-risk-v1-v2-2026-08', 40.44, 3, 40.44, '안전 — 업종·입지 둘 다 양호', '점심시간대(11-14시) 유동인구 243,295명 방향 확인 필요: 배경표본 대비 87백분위로 \'높음\' 쪽인데, 이 카테고리는 통상 \'낮을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '모델 비교군 기준 위험 백분위 40.4%로 분류되었습니다.', '점심 특화 메뉴/프로모션 지원 검토', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'trdar_flpop_lunch', '유동인구 저조', 0.5933260699563552, '점심시간대(11-14시) 유동인구 243,295명 방향 확인 필요: 배경표본 대비 87백분위로 \'높음\' 쪽인데, 이 카테고리는 통상 \'낮을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '점심 특화 메뉴/프로모션 지원 검토', '유동인구 저조 지역은 매출 최소 기준을 완화하는 조항을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'trdar_flpop_dinner', '유동인구 저조', 0.24441799233961417, '저녁시간대(17-21시) 유동인구 343,546명 방향 확인 필요: 배경표본 대비 85백분위로 \'높음\' 쪽인데, 이 카테고리는 통상 \'낮을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '저녁 특화 메뉴/프로모션 지원 검토', '유동인구 저조 지역은 매출 최소 기준을 완화하는 조항을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'adstrd_fd_expndtr', '행정동 소비지출 저조', 0.10203640687886717, '행정동 음식 소비지출 21,006,405,000원 방향 확인 필요: 배경표본 대비 100백분위로 \'높음\' 쪽인데, 이 카테고리는 통상 \'낮을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', '지역 구매력에 연동한 로열티·최소 매출 기준 조정을 검토한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1133, 'closure-risk-v1-v2-2026-08', 69.67, 4, 69.67, '안전 — 업종·입지 둘 다 양호', '행정동 음식 소비지출 21,006,405,000원 방향 확인 필요: 배경표본 대비 100백분위로 \'높음\' 쪽인데, 이 카테고리는 통상 \'낮을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '모델 비교군 기준 위험 백분위 69.7%로 분류되었습니다.', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'adstrd_fd_expndtr', '행정동 소비지출 저조', 1.1119062731645986, '행정동 음식 소비지출 21,006,405,000원 방향 확인 필요: 배경표본 대비 100백분위로 \'높음\' 쪽인데, 이 카테고리는 통상 \'낮을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', '지역 구매력에 연동한 로열티·최소 매출 기준 조정을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'avg_selng_amt_per_store', '상권 매출 침체', 0.7208894123099259, '상권×업종 매장당 추정매출 10,409,964원/월 (배경표본 대비 4백분위 — 예상된 방향과 일치)', '매출 모니터링 주기 단축, 조기 개입', '성과 기반 갱신조건(최소 매출 기준)을 명시한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'trdar_flpop_dinner', '유동인구 저조', 0.24764794689478467, '저녁시간대(17-21시) 유동인구 146,133명 방향 확인 필요: 배경표본 대비 57백분위로 \'높음\' 쪽인데, 이 카테고리는 통상 \'낮을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '저녁 특화 메뉴/프로모션 지원 검토', '유동인구 저조 지역은 매출 최소 기준을 완화하는 조항을 검토한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1137, 'closure-risk-v1-v2-2026-08', 11.81, 1, 0.61, '안전 — 업종·입지 둘 다 양호', '행정동 총 소비지출 42,949,691,000원 방향 확인 필요: 배경표본 대비 80백분위로 \'높음\' 쪽인데, 이 카테고리는 통상 \'낮을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '모델 비교군 기준 위험 백분위 11.8%로 분류되었습니다.', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'adstrd_expndtr_total', '행정동 소비지출 저조', 0.1265127044054084, '행정동 총 소비지출 42,949,691,000원 방향 확인 필요: 배경표본 대비 80백분위로 \'높음\' 쪽인데, 이 카테고리는 통상 \'낮을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', '지역 구매력에 연동한 로열티·최소 매출 기준 조정을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'induty_mclas_nm', '업종 분류', 0.1108785242248481, '업종(분식) 자체의 기본 위험 수준이 반영됨', '업종별 표준 리스크 관리 템플릿 차등 적용', '업종 특성을 반영한 표준 재계약 조항 템플릿을 적용한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'total_initial_cost', '초기 투자비용 부담', 0.08943530227044248, '초기 투자비용 부담 관련 값이 이 브랜드/매장에 결측 — 모델은 결측을 반영해 판단했으나 구체적 수치는 근거로 제시할 수 없음', '초기비용 회수 기간 시뮬레이션 제공, 비용 부담이 큰 가맹점 대상 재협상 지원', '회수 미달 시 유예/분할 조항을 마련한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1138, 'closure-risk-v1-v2-2026-08', 93.53, 5, 93.53, '입지 위험 — 업종은 괜찮으나 이 매장 입지가 나쁨 (상권/접근성 개선 조치)', '상권 매출 침체 관련 값이 이 브랜드/매장에 결측 — 모델은 결측을 반영해 판단했으나 구체적 수치는 근거로 제시할 수 없음', '모델 비교군 기준 위험 백분위 93.5%로 분류되었습니다.', '매출 모니터링 주기 단축, 조기 개입', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'avg_selng_amt_per_store', '상권 매출 침체', 2.130597085808831, '상권 매출 침체 관련 값이 이 브랜드/매장에 결측 — 모델은 결측을 반영해 판단했으나 구체적 수치는 근거로 제시할 수 없음', '매출 모니터링 주기 단축, 조기 개입', '성과 기반 갱신조건(최소 매출 기준)을 명시한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'trdar_cls_sale_mt_gap', '상권 쇠퇴 추세', 2.0125900470309577, '그 상권의 폐업 평균 영업개월이 서울 평균 대비 +15.0개월 차이 방향 확인 필요: 배경표본 대비 97백분위로 \'높음\' 쪽인데, 이 카테고리는 통상 \'낮을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '침체 지역 매장 우선 지원(마케팅/리뉴얼), 상권 등급 재평가', '상권 등급 재평가 결과를 갱신조건에 연동하는 조항을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'avg_competitors_250m', '경쟁밀도', 1.1546268785435463, '반경 250m 내 동일업종 경쟁점포 3개 방향 확인 필요: 배경표본 대비 20백분위로 \'낮음\' 쪽인데, 이 카테고리는 통상 \'높을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '경쟁 밀집 지역 가맹점 대상 포지셔닝 차별화 지원, 신규 출점 시 경쟁밀도 사전 검토', '반경 내 동일업종 신규 출점 제한(상권보호) 조항을 강화하고, 경쟁밀도 급변 시 갱신조건을 재검토한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1144, 'closure-risk-v1-v2-2026-08', 11.81, 1, 2.07, '안전 — 업종·입지 둘 다 양호', '최인접 지하철역까지 510m (배경표본 대비 54백분위 — 예상된 방향과 일치)', '모델 비교군 기준 위험 백분위 11.8%로 분류되었습니다.', '배달 인프라 투자 우선순위 상향, 접근성 낮은 입지는 간판·동선 개선 검토', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'dist_subway_m', '접근성', 0.41924455183438997, '최인접 지하철역까지 510m (배경표본 대비 54백분위 — 예상된 방향과 일치)', '배달 인프라 투자 우선순위 상향, 접근성 낮은 입지는 간판·동선 개선 검토', '접근성이 낮은 입지는 임대료 조건을 재검토하는 조항을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'avg_competitors_500m', '경쟁밀도', 0.33726314706642, '반경 500m 내 동일업종 경쟁점포 2개 방향 확인 필요: 배경표본 대비 3백분위로 \'낮음\' 쪽인데, 이 카테고리는 통상 \'높을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '경쟁 밀집 지역 가맹점 대상 포지셔닝 차별화 지원, 신규 출점 시 경쟁밀도 사전 검토', '반경 내 동일업종 신규 출점 제한(상권보호) 조항을 강화하고, 경쟁밀도 급변 시 갱신조건을 재검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'total_initial_cost', '초기 투자비용 부담', 0.2395355290149002, '초기 투자비용 부담 관련 값이 이 브랜드/매장에 결측 — 모델은 결측을 반영해 판단했으나 구체적 수치는 근거로 제시할 수 없음', '초기비용 회수 기간 시뮬레이션 제공, 비용 부담이 큰 가맹점 대상 재협상 지원', '회수 미달 시 유예/분할 조항을 마련한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1145, 'closure-risk-v1-v2-2026-08', 93.9, 5, 93.9, '입지 위험 — 업종은 괜찮으나 이 매장 입지가 나쁨 (상권/접근성 개선 조치)', '저녁시간대(17-21시) 유동인구 93,527명 (배경표본 대비 38백분위 — 예상된 방향과 일치)', '모델 비교군 기준 위험 백분위 93.9%로 분류되었습니다.', '저녁 특화 메뉴/프로모션 지원 검토', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'trdar_flpop_dinner', '유동인구 저조', 1.136449708298, '저녁시간대(17-21시) 유동인구 93,527명 (배경표본 대비 38백분위 — 예상된 방향과 일치)', '저녁 특화 메뉴/프로모션 지원 검토', '유동인구 저조 지역은 매출 최소 기준을 완화하는 조항을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'adstrd_fd_expndtr', '행정동 소비지출 저조', 1.025369901486977, '행정동 음식 소비지출 910,199,000원 (배경표본 대비 10백분위 — 예상된 방향과 일치)', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', '지역 구매력에 연동한 로열티·최소 매출 기준 조정을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'trdar_cls_sale_mt_gap', '상권 쇠퇴 추세', 0.7413098494437756, '그 상권의 폐업 평균 영업개월이 서울 평균 대비 +1.0개월 차이 방향 확인 필요: 배경표본 대비 68백분위로 \'높음\' 쪽인데, 이 카테고리는 통상 \'낮을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '침체 지역 매장 우선 지원(마케팅/리뉴얼), 상권 등급 재평가', '상권 등급 재평가 결과를 갱신조건에 연동하는 조항을 검토한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1164, 'closure-risk-v1-v2-2026-08', 12.39, 1, 12.39, '안전 — 업종·입지 둘 다 양호', '행정동 총 소비지출 6,482,980,000원 (배경표본 대비 31백분위 — 예상된 방향과 일치)', '모델 비교군 기준 위험 백분위 12.4%로 분류되었습니다.', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'adstrd_expndtr_total', '행정동 소비지출 저조', 0.5471785400351815, '행정동 총 소비지출 6,482,980,000원 (배경표본 대비 31백분위 — 예상된 방향과 일치)', '본사 주도 지역 타겟 마케팅·판촉 지원(로컬 광고/SNS), 발주량·재고 반품 정책 유연화로 매장 비용 부담 완화', '지역 구매력에 연동한 로열티·최소 매출 기준 조정을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'induty_mclas_nm', '업종 분류', 0.22097417634553845, '업종(분식) 자체의 기본 위험 수준이 반영됨', '업종별 표준 리스크 관리 템플릿 차등 적용', '업종 특성을 반영한 표준 재계약 조항 템플릿을 적용한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'trdar_cls_sale_mt_gap', '상권 쇠퇴 추세', 0.13144610872141474, '그 상권의 폐업 평균 영업개월이 서울 평균 대비 -5.0개월 차이 (배경표본 대비 28백분위 — 예상된 방향과 일치)', '침체 지역 매장 우선 지원(마케팅/리뉴얼), 상권 등급 재평가', '상권 등급 재평가 결과를 갱신조건에 연동하는 조항을 검토한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1175, 'closure-risk-v1-v2-2026-08', 11.81, 1, 0.3, '안전 — 업종·입지 둘 다 양호', '상권변화등급 HH', '모델 비교군 기준 위험 백분위 11.8%로 분류되었습니다.', '침체 지역 매장 우선 지원(마케팅/리뉴얼)', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'trdar_chnge_ix', '상권 쇠퇴 추세', 0.2244852373466628, '상권변화등급 HH', '침체 지역 매장 우선 지원(마케팅/리뉴얼)', '상권 등급 재평가 결과를 갱신조건에 연동하는 조항을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'trdar_flpop_lunch', '유동인구 저조', 0.059857736198653054, '점심시간대(11-14시) 유동인구 18,793명 (배경표본 대비 8백분위 — 예상된 방향과 일치)', '점심 특화 메뉴/프로모션 지원 검토', '유동인구 저조 지역은 매출 최소 기준을 완화하는 조항을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'induty_mclas_nm', '업종 분류', 0.04767952628861098, '업종(분식) 자체의 기본 위험 수준이 반영됨', '업종별 표준 리스크 관리 템플릿 차등 적용', '업종 특성을 반영한 표준 재계약 조항 템플릿을 적용한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1177, 'closure-risk-v1-v2-2026-08', 11.81, 1, 1.33, '안전 — 업종·입지 둘 다 양호', '저녁시간대(17-21시) 유동인구 106,727명 (배경표본 대비 44백분위 — 예상된 방향과 일치)', '모델 비교군 기준 위험 백분위 11.8%로 분류되었습니다.', '저녁 특화 메뉴/프로모션 지원 검토', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'trdar_flpop_dinner', '유동인구 저조', 0.4056016149143236, '저녁시간대(17-21시) 유동인구 106,727명 (배경표본 대비 44백분위 — 예상된 방향과 일치)', '저녁 특화 메뉴/프로모션 지원 검토', '유동인구 저조 지역은 매출 최소 기준을 완화하는 조항을 검토한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'total_initial_cost', '초기 투자비용 부담', 0.18889223608490574, '초기 투자비용 부담 관련 값이 이 브랜드/매장에 결측 — 모델은 결측을 반영해 판단했으나 구체적 수치는 근거로 제시할 수 없음', '초기비용 회수 기간 시뮬레이션 제공, 비용 부담이 큰 가맹점 대상 재협상 지원', '회수 미달 시 유예/분할 조항을 마련한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'avg_competitors_250m', '경쟁밀도', 0.1828855763617211, '반경 250m 내 동일업종 경쟁점포 10개 방향 확인 필요: 배경표본 대비 45백분위로 \'낮음\' 쪽인데, 이 카테고리는 통상 \'높을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '경쟁 밀집 지역 가맹점 대상 포지셔닝 차별화 지원, 신규 출점 시 경쟁밀도 사전 검토', '반경 내 동일업종 신규 출점 제한(상권보호) 조항을 강화하고, 경쟁밀도 급변 시 갱신조건을 재검토한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1185, 'closure-risk-v1-v2-2026-08', 11.81, 1, NULL, '업종 기준만 판단 — 입지 정보 없음(서울 외 지역 매장)', '같은 업종의 다른 브랜드들도 최근 해지가 잦음(업종 평균 해지율 15.8%) 방향 확인 필요: 배경표본 대비 43백분위로 \'낮음\' 쪽인데, 이 카테고리는 통상 \'높을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '모델 비교군 기준 위험 백분위 11.8%로 분류되었습니다.', '업종 트렌드 정기 모니터링, 업종 내 수요변화 조기경보, 업종 전환 상담 제공', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'induty_peer_avg_discontinuation_rate', '업종 구조적 위험', 0.0016926831998215288, '같은 업종의 다른 브랜드들도 최근 해지가 잦음(업종 평균 해지율 15.8%) 방향 확인 필요: 배경표본 대비 43백분위로 \'낮음\' 쪽인데, 이 카테고리는 통상 \'높을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '업종 트렌드 정기 모니터링, 업종 내 수요변화 조기경보, 업종 전환 상담 제공', '업종 변경 시 계약 승계·조건 조정 조항을 명확히 하고, 최소 매출 기준 재검토 주기를 단축한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'education_fee', '초기 투자비용 부담', 0.0010453186230900552, '초기 투자비용 부담 관련 값이 이 브랜드/매장에 결측 — 모델은 결측을 반영해 판단했으나 구체적 수치는 근거로 제시할 수 없음', '초기비용 부담이 큰 가맹점 대상 재협상 지원', '회수 미달 시 유예/분할 조항을 마련한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'biz_assurance_amt', '초기 투자비용 부담', 0.0005647884699025103, '초기 투자비용 부담 관련 값이 이 브랜드/매장에 결측 — 모델은 결측을 반영해 판단했으나 구체적 수치는 근거로 제시할 수 없음', '초기비용 회수 기간 시뮬레이션 제공', '회수 미달 시 유예/분할 조항을 마련한다.');

INSERT INTO risk_assessments (store_id, model_version, risk_score, risk_level, location_risk_score, classification_detail, main_reason, prediction, recommended_action, assessed_at) VALUES (1199, 'closure-risk-v1-v2-2026-08', 11.81, 1, NULL, '업종 기준만 판단 — 입지 정보 없음(서울 외 지역 매장)', '같은 업종의 다른 브랜드들도 최근 해지가 잦음(업종 평균 해지율 15.8%) 방향 확인 필요: 배경표본 대비 43백분위로 \'낮음\' 쪽인데, 이 카테고리는 통상 \'높을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '모델 비교군 기준 위험 백분위 11.8%로 분류되었습니다.', '업종 트렌드 정기 모니터링, 업종 내 수요변화 조기경보, 업종 전환 상담 제공', NOW());
INSERT INTO risk_factors (risk_assessment_id, model_version, factor_rank, feature_name, category, shap_contribution, evidence, preventive_action, clause_template) VALUES
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 1, 'induty_peer_avg_discontinuation_rate', '업종 구조적 위험', 0.0016683724276436679, '같은 업종의 다른 브랜드들도 최근 해지가 잦음(업종 평균 해지율 15.8%) 방향 확인 필요: 배경표본 대비 43백분위로 \'낮음\' 쪽인데, 이 카테고리는 통상 \'높을수록\' 위험하다고 가정함 — 실제 관계가 비선형일 수 있으니 조항 적용 전 근거를 다시 확인할 것', '업종 트렌드 정기 모니터링, 업종 내 수요변화 조기경보, 업종 전환 상담 제공', '업종 변경 시 계약 승계·조건 조정 조항을 명확히 하고, 최소 매출 기준 재검토 주기를 단축한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 2, 'education_fee', '초기 투자비용 부담', 0.0010278567676230302, '초기 투자비용 부담 관련 값이 이 브랜드/매장에 결측 — 모델은 결측을 반영해 판단했으나 구체적 수치는 근거로 제시할 수 없음', '초기비용 부담이 큰 가맹점 대상 재협상 지원', '회수 미달 시 유예/분할 조항을 마련한다.'),
  (LAST_INSERT_ID(), 'closure-risk-v1-v2-2026-08', 3, 'biz_assurance_amt', '초기 투자비용 부담', 0.0004912111622039282, '초기 투자비용 부담 관련 값이 이 브랜드/매장에 결측 — 모델은 결측을 반영해 판단했으나 구체적 수치는 근거로 제시할 수 없음', '초기비용 회수 기간 시뮬레이션 제공', '회수 미달 시 유예/분할 조항을 마련한다.');

COMMIT;
-- 총 25개 매장 리스크 평가 반영